# === Base image ===
FROM node:20-alpine

# === Set working directory ===
WORKDIR /app

# === Install global tools ===
RUN npm install -g nodemon

# === Copy package files ===
COPY package*.json ./

# === Install dependencies ===
RUN npm install

# === Copy source code ===
COPY ./src ./src

# === Expose port ===
EXPOSE 3000

# === Command for dev mode ===
CMD ["npm", "run", "dev"]
