name: Deploy to Railway

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Check if RAILWAY_TOKEN is present (safe check)
        run: |
          if [ -z "${RAILWAY_TOKEN}" ]; then
            echo "❌ RAILWAY_TOKEN is not set"
            exit 1
          else
            echo "✅ RAILWAY_TOKEN is available"
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}


      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service websocket --ci
      - name: Notify Deployment Success
        run: echo "Deployment to Railway successful!"